### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '3300000000.0'

### ISSUE THREAD

**Issue by alexlenail** [stemcellcommons/macs2#1]
Seems like whatever I specify for the Effective genome size I get this error.

**Comment by hackdna** [comment]
Thanks for your report. However, this repository is not maintained. I suggest using https://github.com/galaxyproject/tools-iuc/tree/master/tools/macs2 instead.

**Comment by alexlenail** [comment]
Found that, thanks!
